
package api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DAOService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8082/soap?wsdl")
public class DAOService
    extends Service
{

    private final static URL DAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DAOSERVICE_EXCEPTION;
    private final static QName DAOSERVICE_QNAME = new QName("http://service/", "DAOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAOSERVICE_WSDL_LOCATION = url;
        DAOSERVICE_EXCEPTION = e;
    }

    public DAOService() {
        super(__getWsdlLocation(), DAOSERVICE_QNAME);
    }

    public DAOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAOSERVICE_QNAME, features);
    }

    public DAOService(URL wsdlLocation) {
        super(wsdlLocation, DAOSERVICE_QNAME);
    }

    public DAOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAOSERVICE_QNAME, features);
    }

    public DAOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DAOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DAO
     */
    @WebEndpoint(name = "DAOPort")
    public DAO getDAOPort() {
        return super.getPort(new QName("http://service/", "DAOPort"), DAO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DAO
     */
    @WebEndpoint(name = "DAOPort")
    public DAO getDAOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "DAOPort"), DAO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAOSERVICE_EXCEPTION!= null) {
            throw DAOSERVICE_EXCEPTION;
        }
        return DAOSERVICE_WSDL_LOCATION;
    }

}
